---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(flextable)
```

## Marble Coding
```{r}
d <- tibble(p1 = 0,
         p2 = rep(1:0, times = c(1, 3)),
         p3 = rep(1:0, times = c(2, 2)),
         p4 = rep(1:0, times = c(3, 1)),
         p5 = 1)
```


```{r}

d %>% 
  set_names(1:5) %>% 
  mutate(x = 1:4) %>% 
  pivot_longer(-x, names_to = "possibility") %>% 
  mutate(value = value %>% as.character()) %>% 
  
  ggplot(aes(x = x, y = possibility, fill = value)) +
    geom_point(shape = 21, size = 5) +
    scale_fill_manual(values = c("white", "navy"))+
    scale_x_discrete(NULL, breaks = NULL) +
    theme(legend.position = "none")

```


```{r}

tibble(draw    = 1:3,
       marbles = 4) %>% 
  mutate(possibilities = marbles ^ draw) %>% 
  flextable()
```

```{r}

tibble(p_grid = seq(from = 0, to = 1, by = 0.01), 
       prior = c(rep(0, 50), 
                  rep(0.50, 51))
       ) %>% 
       mutate(likelihood = dbinom(x = 5, size = 7, prob = p_grid),
              ustd_posterior = likelihood * prior,
              std_posterior = ustd_posterior/sum(ustd_posterior)
       ) %>% 
  
      ggplot(aes(x = p_grid, y = std_posterior)) +
        geom_line() +
        labs(x = "probability", y = "binomial likelihood") +
        theme(panel.grid = element_blank())
   
```

